### ISSUE TITLE
Mouse buttons support for navigation

### ISSUE THREAD

**Issue by wojtek14** [rodlie/qtfm#77]
It is very practical to use backward/forward mouse buttons for navigation in any file manager, please add it.

**Comment by rodlie** [comment]
Will add. I'm currently hunting down a bug in 6.1, but will add new features after that.

**Comment by rodlie** [comment]
Added support for mouse back button, forward is not supported (required too many changes).

**Comment by k9spud** [comment]
This feature doesn't work for me in QtFM 6.2.1. When I press the mouse's back button, QtFM goes back TWO folders instead of just one. 

I have traced the problem down to the MainWindow::eventFilter() function. The problem is that Qt fires two MouseButtonRelease events from one button click, because the event comes through the "MainWindowClassWindow" object and the "qt_scrollarea_viewport" object as well. 

One possible fix is to "return true;" when the first BackButton event is handled. This will tell Qt's event handling system that we've handled the back mouse button event and don't want any further processing of this event on other objects.

However, this leaves another little problem that I don't know how to fix: if I double click the Back mouse button, sometimes QtFM can mis-interpret this as a double left click action, which makes QtFM briefly open a folder and immediately go back, or open a file (depending on where my mouse pointer is at the moment I double click the Back mouse button).
